//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterPiece_UsingMVCBackEnd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_
    {
        public int id { get; set; }
        public string product_id { get; set; }
        public string pass { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public string adress { get; set; }
        public Nullable<int> phoneNo { get; set; }
    }
}
